Env = "local"
BotToken = "7246294865:AAHbRfz94f2BBfn01LDiiHm9wGQ79C6koOA"
BotID = "7377411543896129542"
APIToken = "pat_CjCQHC63JZDMX2vEIio039dHvekk6K01nVs0Q5dvmhRmx5sodA3zpV4F8jHIOzaL"
APIUrl = "https://api.coze.com/open_api/v2/chat"
ChannelID = -1002202044566
PaymentProviderAPIKey = "381764678:TEST:86962"

GenAPIKey = "sk-TujSvEl4cyo0prswcKkVLWsxK9Vbsev8d09T4Xh4yFmsuOC9dwGubiuaDCfj"
GenAPIUrl = "https://api.gen-api.ru/api/v1/networks/chat-gpt-4-turbo"