name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-deploy:
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Build
      run: go build -ldflags "-w -v" cmd/main.go

    - name: Copy file to server
      run: scp -i ${{ secrets.SSH_KEY }} ./main ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/aibot/main
    - name: Run Command on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          pm2 restart 6 --update-env
