name: Audit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'
    - name: Verify dependencies
      run: go mod verify
    - name: Build
      run: go build -ldflags "-w -v" cmd/main.go
    - name: Run go vet
      run: go vet $(go list ./... | grep -v /vendor/)
    - name: Install golint
      run: go install golang.org/x/lint/golint@latest
    - name: Run golint
      run: golint $(go list ./... | grep -v /vendor/)
    - name: Run tests
      run: go test -race -vet=off $(go list ./... | grep -v /vendor/)